services:
  web:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - ./backend/.env   # ← or ".env" if your file lives next to this compose file
    environment:
      REDIS_HOST: redis
      PYTHONUNBUFFERED: "1"
      FLASK_ENV: production

  redis:
    image: redis:latest
