version: "3.9"

services:
  web:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    # ports:
    #   - "6379:6379"
