[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "httpie>=3.2.4",
    "openai>=1.95.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
]
